/*
 * option.h
 *
 * Created: 22/10/2558 11:42:22
 *  Author: Pan
 */ 


#ifndef OPTION_H_
#define OPTION_H_

enum {
	OPTION_OIL_DATA,
	OPTION_EXTEND_MSR,
	OPTION_HAHD_OD,
	OPTION_HAHD_GPS,
	OPTION_CUT_START,
	OPTION_RFID,
	OPTION_LICENCE_CARD,
	OPTION_TEMP_SENSOR,
	OPTION_DELAY_OVSPEED,
	OPTION_PTO1_STATUS,
	OPTION_PTO2_STATUS,
	OPTION_PTO3_STATUS,
	OPTION_SPEAKER,
	OPTION_SERL_CAM,
	OPTION_SLOW_MACHINE,
	OPTION_RPM,
	OPTION_HOLDON_BUZZER_OVSPEED,
	OPTION_DISTANCE_WITHOUT_IG,
	OPTION_LED_OPT_BY_PTO2,
	OPTION_LED_OPT_BY_OPTION,
	OPTION_ALARM_PARK_BY_IG_ON,
	OPTION_DONT_BUFFER_DATA,
	OPTION_ALARM_NO_RFID_INSERT
};



#endif /* OPTION_H_ */