/*
 * adl_traces_Private.h
 *
 * Created: 27/2/2558 17:13:45
 *  Author: pan
 */ 


#ifndef ADL_TRACES_PRIVATE_H_
#define ADL_TRACES_PRIVATE_H_

#define ADL_TRACES_LEV00_EN	0
#define ADL_TRACES_LEV01_EN	0
#define ADL_TRACES_LEV02_EN	0
#define ADL_TRACES_LEV03_EN	0
#define ADL_TRACES_LEV04_EN	0
#define ADL_TRACES_LEV05_EN	0
#define ADL_TRACES_LEV06_EN	0
#define ADL_TRACES_LEV07_EN	0
#define ADL_TRACES_LEV08_EN	0
#define ADL_TRACES_LEV09_EN	0
#define ADL_TRACES_LEV10_EN	0
#define ADL_TRACES_LEV11_EN	0
#define ADL_TRACES_LEV12_EN	0
#define ADL_TRACES_LEV13_EN	0
#define ADL_TRACES_LEV14_EN	0
#define ADL_TRACES_LEV15_EN	0
#define ADL_TRACES_LEV16_EN	0
#define ADL_TRACES_LEV17_EN	0
#define ADL_TRACES_LEV18_EN	0
#define ADL_TRACES_LEV19_EN	0
#define ADL_TRACES_LEV20_EN	0
#define ADL_TRACES_LEV21_EN	0
#define ADL_TRACES_LEV22_EN	0
#define ADL_TRACES_LEV23_EN	0
#define ADL_TRACES_LEV24_EN	0
#define ADL_TRACES_LEV25_EN	0
#define ADL_TRACES_LEV26_EN	0
#define ADL_TRACES_LEV27_EN	0
#define ADL_TRACES_LEV28_EN	0
#define ADL_TRACES_LEV29_EN	0
#define ADL_TRACES_LEV30_EN	0




#endif /* ADL_TRACES_PRIVATE_H_ */